Additional chart override options
evidence-dev/evidence pull request #1598
Opened 2024-02-14 03:58 UTC by hughess

### Description

These options can be applied to any standard cartesian charts in Evidence:
- `renderer` - "canvas" (default) or "svg"
```
renderer=svg
```
- `seriesOptions` - ECharts options to be applied to all series in a chart. This will loop through the series to apply the changes (e.g., setting a border around data points)
```
seriesOptions={{
   itemStyle: {
      borderWidth: 4,
      borderColor: '#c8c8c8'
   }
}}
```
This option skips reference lines and reference areas when looping through series - this avoids unintended consequences, but also restricts the ability to edit those items. We may need to offer another way to access them. In the meantime, they are accessible through `echartsOptions` by specifying `series` changes to the correct series index locations.

- `seriesColors` - option to set a specific colour for a specific series, specified by name
```
seriesColors={{
   'Canada': 'red',
   'UK': 'navy'
}}
```

![CleanShot 2024-02-13 at 22 57 39@2x](https://github.com/evidence-dev/evidence/assets/12602440/c6de918c-57a5-4388-8f2d-0f6c0474f2b3)

```html
<LineChart 
  data={simpler_bar} 
  x=year 
  y=value 
  series=country
  seriesColors={{
    'Canada': 'red',
    'US': 'navy'
  }}
/>
```

This PR also adjusts the rendering timing in `echarts.js` to avoid reloading of the charts where possible. This is a short-term solution that should be cleaned up in the future.

### Checklist

- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

2024-02-16 14:35 UTC, hughess commented
@ItsMeBrianD @csjh would be great to get your eyes on this one - in particular the changes to `echarts.js` 

I shifted some things around and added a delay on initial load to avoid multiple requests. I initially tried debounce, but that seemed to cause issues with charts hooked up to input components.

2024-02-22 15:06 UTC, ItsMeBrianD requested changes
Too much duplicated code here; happy to pair and/or take a stab at pulling it out into a shared set of functions to reduce that.

Also unclear why versions were updated in this package, we likely want to revert those changes to avoid interfering with the release.

Otherwise looks good

2024-02-22 15:06 UTC, ItsMeBrianD commented on packages/component-utilities/package.json
>  	"description": "",
Why did versions get updated in this PR?

2024-02-22 15:06 UTC, ItsMeBrianD commented on packages/component-utilities/src/echartsCanvasDownload.js
> +	const applySeriesColors = () => {
Why is this being duplicated? Could these functions be pulled out into a shared file?

2024-02-22 20:40 UTC, ItsMeBrianD approved these changes

2024-02-22 20:43 UTC, merged

2024-02-23 22:50 UTC, archiewood commented
This is missing docs

2024-02-23 22:52 UTC, hughess commented
Ah damn, completely missed that. Will add them!