Date range default value
evidence-dev/evidence pull request #1988
Opened 2024-05-08 18:18 UTC by Franreno

### Description

This PR aims to add a defaultValue parameter to the DateRange input component.
The defaultValue has the purpose to define a default range when the component is first loaded.

To use is to simply add the defaultValue as below:
```js
<DateRange 
    data={orders_by_month} 
    dates=month 
    name=range_default 
    defaultValue="Last 90 days"
/>
```
Then, the DateRange will initialize with the defaultValue provided

<img width="755" alt="Screenshot 2024-05-08 at 19 14 02" src="https://github.com/evidence-dev/evidence/assets/67326251/1d23832b-1d5d-4380-a55b-70a3c4e7c196">

If the parameter is not provided or does not comply with the labels available on the `preset` variable, then the component's behavior should be the same as previously

<img width="745" alt="Screenshot 2024-05-08 at 19 13 52" src="https://github.com/evidence-dev/evidence/assets/67326251/ce2531b1-7e28-43b8-9dc5-cc3c201a0bc1">

Closes #1984

### Checklist

- [ ] For UI or styling changes, I have added a screenshot or gif showing before & after
- [X] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [ ] I have added to the docs where applicable
- [ ] I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable

2024-05-16 14:59 UTC, ItsMeBrianD commented on .changeset/early-crews-compete.md
> +Add defaulValue to DateRange
```suggestion
Add defaultValue to DateRange
```

2024-05-16 19:13 UTC, Franreno commented on .changeset/early-crews-compete.md
> +Add defaulValue to DateRange
Ops, thanks :D

2024-05-17 15:03 UTC, mcrascal requested changes
This is awesome, I like this string based API for selecting default date ranges. 

The only thing that seems off to me here is the loading behaviour. It seems that in the process of loading, results from queries that depend on the value here transition through an empty state, causing a no data error to be briefly visible in dependent components. @ItsMeBrianD can probably help identify the issue. 

![CleanShot 2024-05-17 at 10 56 17](https://github.com/evidence-dev/evidence/assets/6857673/cd8ee76b-0112-4e05-8e9e-1b9dbc8f8d81)

2024-06-05 15:23 UTC, ItsMeBrianD commented
> The only thing that seems off to me here is the loading behaviour. It seems that in the process of loading, results from queries that depend on the value here transition through an empty state, causing a no data error to be briefly visible in dependent components. @ItsMeBrianD can probably help identify the issue.

I think this was fixed in `features/b`, merging next in should resolve the issue

2024-06-17 23:19 UTC, archiewood commented
@kwongz was this addressed by your PR? Can we close this?

2024-06-17 23:43 UTC, kwongz commented
@archiewood  Yup! Default Values are now available as of the latest updates

2024-06-17 23:48 UTC, closed without merging