fix: drop down gap
evidence-dev/evidence pull request #2007
Opened 2024-05-14 14:21 UTC by kwongz

### Description

### Checklist

- [ x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [ x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [ ] ~~I have added to the docs where applicable~~
- [ ] ~~I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable~~

2024-05-14 17:06 UTC, ItsMeBrianD requested changes

2024-05-14 17:06 UTC, ItsMeBrianD commented on packages/ui/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
> +	//kwongz created static variable for displayed options, handle height based on number of options
Remove comment

2024-05-14 17:06 UTC, ItsMeBrianD commented on packages/ui/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
> +								<!-- kwongz height handle by function, passing Displayed_Options to component for handling overflow (scroll) -->
Remove Comment

2024-05-14 17:06 UTC, ItsMeBrianD commented on packages/ui/core-components/src/lib/atoms/inputs/dropdown/Virtual.svelte
> +	// kw added displayedOption value from Dropdown.svelte
Remove comment

2024-05-14 17:06 UTC, ItsMeBrianD commented on packages/ui/core-components/src/lib/atoms/inputs/dropdown/Virtual.svelte
> +
Remove console.log

2024-05-14 17:06 UTC, ItsMeBrianD commented on packages/ui/core-components/src/lib/atoms/inputs/dropdown/Virtual.svelte
> +<!-- kwongz added tenerary operation for scroll depending on items and displayed options value -->
Remove comment

2024-05-14 17:06 UTC, ItsMeBrianD commented on packages/ui/core-components/src/lib/atoms/inputs/dropdown/Virtual.svelte
> +	style="height: {height}; overflow: {items < displayedOptions ? 'hidden' : 'auto'};"
We should double check that we need this here - modifying the height (currently 32px) per option to being slightly higher is probably the fix we want here

2024-05-14 17:06 UTC, ItsMeBrianD commented on packages/ui/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
> +									displayedOptions={DISPLAYED_OPTIONS}
I don't know if we want VirtualList to be aware of this - it shouldn't be responsible for knowing about this

2024-05-14 17:06 UTC, ItsMeBrianD commented on packages/ui/core-components/src/lib/atoms/inputs/dropdown/Dropdown.svelte
> +	}
:fire:

2024-05-15 16:02 UTC, ItsMeBrianD approved these changes

2024-05-15 23:03 UTC, mcrascal commented
@kwongz hitting the ground running, nice! 

A couple things I noticed: 

1. Dropdown items can wrap to multiple lines. Right now, a dropdown with a wrapping item ends up a little cut off. 
2. Check the behaviour when searching, see gif. Ideally, all results would be visible, up to a height maximum, but right now the menu is shrinking below the size of the list. 

@ItsMeBrianD feel free to weigh in also, but would it make sense to have the behaviour be something more like:   

1. More than [5] list items: we render the virtual list, and it has the same fixed height always. 
2. Less than [5] list items: we render a div, and we just let it fit its contents (e.g. no fixed height)? 

I think that would cover the multi-line and search scenarios while also removing the gap. 

![CleanShot 2024-05-15 at 18 39 01@2x](https://github.com/evidence-dev/evidence/assets/6857673/b911dfc3-0fac-42e2-aa84-8c9ac7b4ed70)

![CleanShot 2024-05-15 at 18 39 35](https://github.com/evidence-dev/evidence/assets/6857673/8f32d814-b137-4eb1-8567-45b8e34bb6be)

2024-05-15 23:04 UTC, mcrascal requested changes
See comment

2024-05-16 13:28 UTC, kwongz commented
Thanks @mcrascal! Sound good, get working on this!

2024-05-16 19:33 UTC, kwongz commented
Added conditional rendering in the Dropdown.svelte file, Renders scroll-able Virtual List with 5 or more options

![image](https://github.com/evidence-dev/evidence/assets/69778837/6d485403-b47e-4e3e-822a-651109d3ebf5)

Dropdowns with less then 5 options will render DropdownOptionDisplay component with a regular div container to manage the height of the contents

Example 1.  - 4 options with Line breaking

![image](https://github.com/evidence-dev/evidence/assets/69778837/9cbba20b-af72-49e0-bcfe-a2a10c12c48e)

Example 2.  - 2 options

![image](https://github.com/evidence-dev/evidence/assets/69778837/51746971-2d9c-483e-a1c2-b1f60d9c6a6c)

2024-05-16 20:10 UTC, mcrascal commented on packages/ui/core-components/.evidence-queries/sources/hashes.json
I believe this should be gitignored

2024-05-16 20:11 UTC, mcrascal approved these changes
Very excellent. ~No notes~. One note.

2024-05-16 20:57 UTC, kwongz commented on packages/ui/core-components/.evidence-queries/sources/hashes.json
Thanks! Added the hashes.json to the gitignore, not too sure how it ended up there will speak to Brian about it tomorrow

2024-05-17 19:25 UTC, merged

2024-05-17 19:35 UTC, mcrascal commented
@kwongz Massive!