Query Debugger
evidence-dev/evidence pull request #2112
Opened 2024-06-17 15:29 UTC by ItsMeBrianD

### Description

### Checklist

- [ ] For UI or styling changes, I have added a screenshot or gif showing before & after
- [ ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [ ] I have added to the docs where applicable
- [ ] I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable

2024-07-11 15:27 UTC, ItsMeBrianD commented
@mcrascal where/when do we want to land this?

2024-09-09 16:43 UTC, zachstence requested changes

2024-09-09 16:43 UTC, zachstence commented on packages/ui/core-components/src/lib/atoms/inputs/dropdown/dropdownOptionStore.spec.js
> +				expect(get(options)).toStrictEqual(opts.reverse());
Why is this change necessary?

2024-09-09 16:43 UTC, zachstence commented on packages/ui/core-components/src/lib/devtools/input-debug/Diff.svelte
> +	// TODO: rewrite this to be a little more accurate
More accurate how? We should remove this comment or add more context

2024-09-09 16:43 UTC, zachstence commented on packages/lib/sdk/src/utils/svelte/inputs.js
> +export const readonlyInputContext = () => {
```suggestion
export const getReadonlyInputContext = () => {
```

2024-09-09 16:43 UTC, zachstence commented on packages/ui/core-components/src/lib/devtools/query-debugger/QueryDebugger.svelte
> +	// TODO: is this needed?
?

2024-09-09 16:43 UTC, zachstence commented on packages/ui/core-components/src/lib/devtools/query-debugger/QueryDebugger.svelte
> +	// };
Remove these comments?

2024-09-09 16:43 UTC, zachstence commented on packages/ui/core-components/src/lib/devtools/query-debugger/sections/Verbose.svelte
> +				<!-- TODO: Make sure we don't render in initialData completely -->
TODO?

2024-09-09 16:45 UTC, zachstence approved these changes

2024-09-09 16:48 UTC, ItsMeBrianD commented on packages/ui/core-components/src/lib/atoms/accordion/AccordionItem.svelte
> +		<BaseAccordion.Trigger class={compact ? 'py-0' : ''}>
Needs documentation

2024-09-09 16:49 UTC, ItsMeBrianD commented on packages/ui/core-components/src/lib/atoms/hint/Hint.svelte
> +
documentation

2024-09-09 21:18 UTC, merged