Area, Point, Bubble Maps Drill Down + Invisible Links
evidence-dev/evidence pull request #2224
Opened 2024-07-16 22:23 UTC by kwongz

### Description

### Checklist

- [ ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [ ] I have added to the docs where applicable

2024-07-17 15:23 UTC, kwongz commented
merged feature branch in, still getting error 

![image](https://github.com/user-attachments/assets/64a68b12-f06a-43f0-9e4c-76dcc9b23976)

Updated branch with pnpm install --no-frozen-lockfile, but still getting the error in the picture above

@ItsMeBrianD @zachstence

2024-07-17 15:42 UTC, archiewood commented
@kwongz if you haven't already tried, `pnpm i` and merging the result sometimes fixes this

2024-07-17 15:57 UTC, zachstence commented
@kwongz Looks like its working now. I just did `pnpm i --ignore-scripts` and committed/pushed the updated `pnpm-lock.yaml`.

2024-07-17 16:03 UTC, kwongz commented
Thanks All!

2024-07-22 16:46 UTC, zachstence requested changes

2024-07-22 16:46 UTC, zachstence commented on packages/ui/core-components/src/lib/unsorted/viz/map/BaseMap.svelte
> +		<svelte:fragment slot="skelton"></svelte:fragment>
Is `skelton` supposed to be `skeleton`?

2024-07-22 16:46 UTC, zachstence commented on packages/ui/core-components/src/lib/unsorted/viz/map/BaseMap.svelte
> +		<svelte:fragment slot="skelton"></svelte:fragment>
Is `skelton` supposed to be `skeleton`?

2024-07-22 16:46 UTC, zachstence commented on packages/ui/core-components/src/lib/unsorted/viz/map/EvidenceMap.js
> +						this.map.doubleClickZoom.disable();
It seems a little weird to disable the `doubleClickZoom` only after the user has double clicked the map. Maybe this should happen when the map is created if they provide links?

2024-07-22 16:46 UTC, zachstence commented on packages/ui/core-components/src/lib/unsorted/viz/map/EvidenceMap.js
> +				this.map.doubleClickZoom.disable();
See other comment

2024-07-22 16:46 UTC, zachstence commented on packages/ui/core-components/src/lib/unsorted/viz/map/EvidenceMap.js
> +		console.log(tooltip);
```suggestion
```

2024-07-22 22:06 UTC, zachstence commented
@ItsMeBrianD Do we care about this Vercel deployment? Not sure what it is or why its failing

2024-07-23 13:42 UTC, hughess commented
@kwongz the area map click target is different than I would have expected - it seems like you need to click the specific line point rather than being able to click the area itself.

I know there's some echarts limitations with that, but is there a way to enable the clicks for the area?

2024-07-24 05:04 UTC, kwongz commented
Sorry @hughess I think i'm misunderstanding, but on my end i can double click the areas in Area Map to navigate to the link.
I'm unclear on line point vs area? 

https://www.loom.com/share/f19742b9003b4a8eb3f2069cd6ad55c8

2024-07-24 11:48 UTC, hughess commented
Sorry @kwongz i meant to say area _chart_!

area map is working for me

2024-07-24 17:25 UTC, kwongz commented
@hughess, I understand now, yeah that would be a nice fix. I'll make a new issue for this since Area Charts was in another PR thats been merged in the the feature

Thanks!

2024-07-24 17:36 UTC, hughess commented
@kwongz makes sense.

The same issue exists on the line chart, where you have to click the specific point rather than being able to click the line itself. For some line charts with a small # of points, this will cause issues for users who won't be over a point when they try to click.

Ideal would be that the click target for the line chart is the full line, and for the area it's the full area

2024-07-24 21:11 UTC, merged