added oncscroll of prop sections of docs
evidence-dev/evidence pull request #2324
Opened 2024-08-13 18:29 UTC by kwongz

### Description

### Checklist

- ~~For UI or styling changes, I have added a screenshot or gif showing before & after~~
- ~~I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)~~
- ~~I have added to the docs where applicable~~
- ~~I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable~~

2024-08-13 18:43 UTC, kwongz commented
Added <a href="#props-{name}" to doc's prop section. 

Click on Value, scrolls you to Value in prop section, as well as updates the url (/components/big-value/#props-value)

![image](https://github.com/user-attachments/assets/d7956262-b289-41a0-90bb-7de41733a7f1)
https://www.loom.com/share/6d859aa798c54eb2921146b1ad2900f2

Entering that URL in a new tab will scroll to the specified section once the page opens. However, an existing issue was discovered: In the example video, the Big Value component loads after the initial scroll. This change affects the height of the page, causing the viewport's scroll position to shift, so the intended scroll position is no longer accurate.

Test example for Current Docs site & Local branch with prop scroll
https://www.loom.com/share/233bc359290f4d61a533576265d8ffcb

2024-08-14 20:34 UTC, kwongz commented
Changed URL event listener in onMount, to fix build errors I was experiencing. 

Concern: Is it an issue that all PropListing Components have an event listener for the hash changes?

2024-08-15 13:30 UTC, kwongz commented
Event listener logic handled in context='module', created and removed once per page

2024-08-28 14:17 UTC, kwongz commented
fix #2119

2024-08-29 15:19 UTC, ItsMeBrianD approved these changes
lgtm assuming the id / indexing here is stable

2024-08-29 15:19 UTC, ItsMeBrianD commented on sites/docs/components/PropListing.svelte
> +		}
Is this going to be stable when multiple of the same component appear?

This looks good to me, but is probably a good candidate for unit testing though

2024-08-29 15:20 UTC, ItsMeBrianD requested changes
Changeset

2024-09-04 16:46 UTC, ItsMeBrianD approved these changes

2024-09-04 16:46 UTC, merged