[Theming] Use themes in colors in Javascript
evidence-dev/evidence pull request #2655
Opened 2024-10-16 21:47 UTC by zachstence

### Description

### Checklist

- [ ] For UI or styling changes, I have added a screenshot or gif showing before & after
- [ ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [ ] I have added to the docs where applicable
- [ ] I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable

2024-10-17 18:16 UTC, ItsMeBrianD requested changes

2024-10-17 19:55 UTC, zachstence commented on packages/ui/core-components/src/lib/unsorted/ui/Tabs/TabDisplay.svelte
> -	}
No, the background color has opacity applied here via `chroma-js`

https://github.com/evidence-dev/evidence/blob/87d18a692c84d3649925f8fe5cbbe6f12c23b0d0/packages/ui/core-components/src/lib/unsorted/ui/Tabs/TabDisplay.svelte#L11

2024-10-17 19:56 UTC, zachstence commented on packages/ui/core-components/src/lib/unsorted/viz/map/_USMap.svelte
> +		}
I only changed indentation here, and I want to keep this PR as much theming-only as possible, so I'm not going to refactor any JS code

2024-10-17 19:57 UTC, zachstence commented on packages/ui/core-components/src/lib/unsorted/viz/map/_USMap.svelte
> +			);
[4d69ac2](https://github.com/evidence-dev/evidence/pull/2655/commits/4d69ac2886cf79b22a3a3b008ffa250159254da8)

2024-10-17 19:57 UTC, zachstence commented on packages/ui/core-components/src/lib/unsorted/ui/Tabs/Tabs.svelte
> +	export let color;
[75120cb](https://github.com/evidence-dev/evidence/pull/2655/commits/75120cbb38a8aac3a09e13b48fa79226e8906119)

2024-10-17 19:57 UTC, zachstence commented on packages/ui/core-components/src/lib/themes.js
> + * TODO could use some help naming activeTheme / theme
[87d18a6](https://github.com/evidence-dev/evidence/pull/2655/commits/87d18a692c84d3649925f8fe5cbbe6f12c23b0d0)

2024-10-17 19:57 UTC, zachstence commented on packages/lib/component-utilities/src/echarts.js
> +			});
[f590998](https://github.com/evidence-dev/evidence/pull/2655/commits/f59099822da76b65b129eb7b6b5cdfc97b7bfbc0)

2024-10-17 19:57 UTC, zachstence commented on packages/lib/component-utilities/src/echarts.js
> + * } Options
[262ca2d](https://github.com/evidence-dev/evidence/pull/2655/commits/262ca2d1287c57bc8774d79b00a88f5c71270089)

2024-10-17 20:02 UTC, zachstence commented on packages/ui/core-components/jsconfig.json
> +		"types": ["@evidence-dev/tailwind"]
[9b2e673](https://github.com/evidence-dev/evidence/pull/2655/commits/9b2e6737c7b52572d01564186b54a4895170a18f)

2024-10-18 15:12 UTC, ItsMeBrianD approved these changes

2024-10-18 16:13 UTC, merged