Stories: removed double query loading, Reference: added empty skeleton
evidence-dev/evidence pull request #2761
Opened 2024-11-11 20:55 UTC by kwongz

### Description

### Checklist

- [ ] For UI or styling changes, I have added a screenshot or gif showing before & after
- [ ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [ ] I have added to the docs where applicable
- [ ] I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable

2024-11-11 21:25 UTC, kwongz commented
![{6D8EAD90-81C7-4AFC-97A4-E52830AF9DBD}](https://github.com/user-attachments/assets/81c0f42a-6dec-4b93-abaf-271893f2d22a)

Still occuring with change

2024-11-11 21:25 UTC, ItsMeBrianD requested changes
Got a few stray console logs in here

2024-11-11 21:40 UTC, kwongz commented
No More Layout shift

https://www.loom.com/share/533655bf94e6479482dddbeac346662d?sid=4a58dd53-393e-4b62-aed3-82945c738fe0

2024-11-11 21:44 UTC, kwongz commented on packages/ui/core-components/src/lib/unsorted/viz/references/ReferenceArea/ReferenceArea.stories.svelte
> -		<QueryLoad data={referenceAreaData}>
Query load already exists in annotation components, causing skeletons to render unnecessarily in stories

2024-11-11 21:46 UTC, kwongz commented on packages/ui/core-components/src/lib/unsorted/viz/references/ReferenceArea/ReferenceArea.stories.svelte
> +		</LineChart>
Depicts similar env as bug experienced https://sf311.evidence.app/neighborhoods/OUTER%20SUNSET/

2024-11-12 16:47 UTC, ItsMeBrianD approved these changes

2024-11-12 17:24 UTC, hughess commented
1 thing I think is worth checking - are the annotation components still reactive to changes in data? 

I think we had that problem before changing them to QueryLoad, so just want to make sure we aren't regressing that

2024-11-12 20:45 UTC, kwongz commented
Annotations accepting dynamic Data from dropdown

![image](https://github.com/user-attachments/assets/062b1c1b-1528-445e-b616-b7b9a6030767)
![image](https://github.com/user-attachments/assets/958d378b-3ffd-448e-a6cb-a027f2b2abb3)

2024-11-12 21:08 UTC, kwongz commented
Hi @hughess, sorry for the miscommunication, Annotations accepting dynamic data is working alongside the layout shift fix.
If this looks good its ready to merge.

Thanks!

Dynamic data w/ Annotation + Dropdown 

![image](https://github.com/user-attachments/assets/434cc31e-c48c-4170-a84e-a5ecade6bd6c)


https://www.loom.com/share/1a350c9ba66643bdaceefc4d91de94de?sid=cd2ec098-b4e1-482a-b7c8-522a65fde27d

2024-11-13 21:47 UTC, hughess approved these changes

2024-11-13 21:49 UTC, merged