Fixes bug where DataTable component throws error when underlying columns in data change
evidence-dev/evidence pull request #2827
Opened 2024-11-21 09:35 UTC by jantaks

### Background:
I wanted to create a DataTable for the result of a PIVOT operation when i found that this component could not deal with the underlying column IDs changing. 

The issue is caused by 2 pieces of state (columns and columSummary) that are not updated in the correct sequence during the rendering process. 

See storybook: /story/viz-datatable--reactive-datatable

### Before:
![before](https://github.com/user-attachments/assets/96e3d6f6-152f-4ccf-b946-16110e3833ff)

### After:
![after](https://github.com/user-attachments/assets/15ed641d-d607-4b8c-9677-08ea587e16a0)

### Checklist

- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [x] I have added to the docs where applicable
- [x] I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable

2024-11-21 15:23 UTC, zachstence commented
Looks like some of the DataTable stories are encountering an error when building Storybook
![image](https://github.com/user-attachments/assets/6696d7b1-7813-48c4-9fe6-c4827b714369)

2024-11-25 20:22 UTC, ItsMeBrianD approved these changes

2024-11-25 21:38 UTC, zachstence requested changes
Hey @jantaks, seems like there's still an issue with the `DataTable`. Our `base-path` and `prerender` E2E tests are failing. I pulled down your branch and tried to run `e2e/base-path` and when I go to the `/table-row-links` page, everything freezes. Seems like there's some infinite reactivity update happening.

2024-11-27 09:34 UTC, jantaks commented
HI @zachstence, thanks for the feedback. I guess I should have caught this myself. This my first open source contribution ever so I am still learning.  Anyways ....  will look into it.

2024-11-27 15:43 UTC, zachstence commented
> HI @zachstence, thanks for the feedback. I guess I should have caught this myself. This my first open source contribution ever so I am still learning. Anyways .... will look into it.

No worries, we appreciate the contribution!

2024-12-17 16:05 UTC, ItsMeBrianD commented
@kwongz can you take a look and see if we can get this across the line?

2024-12-19 06:13 UTC, jantaks commented
> @kwongz can you take a look and see if we can get this across the line?

I have spent quite some time trying to resolve this. The issue for me was that there are quite a lot of interdependent reactive statements / effects in this component. I went down the route of externalizing the state in an external store but things got too complicate to wrap my head around. Typescript and Svelte5 would make this task a lot easier ...

2025-01-02 15:29 UTC, archiewood commented
Hi @jantaks - I'm going to close this for now - If you get it working, feel free to reopen!

2025-01-02 15:29 UTC, closed without merging