Add tests for (real world) package installation
evidence-dev/evidence pull request #2870
Opened 2024-11-29 20:51 UTC by csjh

### Description

Adds an e2e test that packs every package into tarballs and installs from those using npm

2024-11-29 21:09 UTC, csjh commented
Not sure where to put the `node ./build-deps-to-tgz.js && npm i` step so it's in sources for now

2024-11-29 21:10 UTC, csjh commented
And need to move away from `import("fs").glob` for the node 18 suite

2024-12-02 21:03 UTC, csjh commented
`e2e/packaging` tests are expected to fail until #2866 merges

2024-12-03 20:12 UTC, zachstence requested changes

2024-12-03 20:12 UTC, zachstence commented on .github/workflows/e2e.yml
> +      - name: Run setup
I'd rather not modify all the `e2e` projects to have a `setup` script.

Instead, can you add another step to this workflow to run `setup` if it exists?

```sh
pnpm run --if-present setup
```

2024-12-03 20:12 UTC, zachstence commented on package.json
> +		"glob": "11.0.0"
Install this as a `devDependency` in `e2e/package.json` instead of the root `package.json`

2024-12-03 20:12 UTC, zachstence commented on pnpm-workspace.yaml
> +  - '!e2e/packaging'
Add a comment why this is excluded

2024-12-04 21:13 UTC, merged