Fix virtual source configs
evidence-dev/evidence pull request #2916
Opened 2024-12-13 22:17 UTC by csjh

### Description

fixes datasources that use virtual/references, adds tests, logs info when source updating errors in debug mode

not totally sure this is the proper fix, still not 100% sure of what `Options.ownKeys` semantically represents (I'm understanding it as the keys of the given options that have materialized values in the schema? Or something like that)

### Checklist

- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

2024-12-15 18:32 UTC, ItsMeBrianD requested changes

2024-12-15 18:32 UTC, ItsMeBrianD commented on sites/example-project/src/pages/settings/+page.server.js
> +				console.error(e);
Use the logger instead of console here

2024-12-18 19:46 UTC, ItsMeBrianD commented on sites/example-project/src/pages/settings/+page.server.js
> +			if (e.stack) log.debug(e.stack);
```suggestion
			log.debug(`error updating sources: ${e}`, {error: e});
```

2024-12-19 17:23 UTC, archiewood approved these changes

2024-12-19 17:23 UTC, merged