JavaScript Connector
evidence-dev/evidence pull request #2935
Opened 2024-12-18 23:23 UTC by archiewood

### Description

### Checklist

- [ ] For UI or styling changes, I have added a screenshot or gif showing before & after
- [ ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)
- [ ] I have added to the docs where applicable
- [ ] I have added to the [VS Code extension](https://github.com/evidence-dev/evidence-vscode) where applicable

2024-12-19 17:02 UTC, ItsMeBrianD requested changes

2024-12-19 17:02 UTC, ItsMeBrianD commented on packages/datasources/javascript/test/test.js
> +		await runner('', './test/files/empty.js');
There's a tool called `mock-fs` that is better than having a bunch of files floating around:

Example Usage:
https://github.com/evidence-dev/evidence/blob/next/packages/lib/preprocess/src/partials/inject-partials.spec.js#L5-L9

2024-12-19 17:02 UTC, ItsMeBrianD commented on packages/datasources/javascript/index.js
> +									: EvidenceType.STRING,
This doesn't seem to have support for booleans

2024-12-19 17:02 UTC, ItsMeBrianD commented on packages/datasources/javascript/index.js
> +									: EvidenceType.STRING,
We also have this logic built-in to `db-commons`:
https://github.com/evidence-dev/evidence/blob/next/packages/lib/db-commons/index.cjs#L31-L88

2024-12-19 17:05 UTC, archiewood commented on .changeset/soft-carrots-stare.md
> +'@evidence-dev/javascript': patch
This is consistent with all other connectors 

but i appreciate the issue - bigquery is clear but javascript is not

how about `@evidence-dev/javascript-connector`

2025-01-02 15:56 UTC, archiewood commented on packages/datasources/javascript/package.json
> +    "@evidence-dev/plugin-connector": "^2.1.15",
adjusted

2025-01-02 16:56 UTC, archiewood commented on packages/datasources/javascript/index.js
> +									: EvidenceType.STRING,
This built in logic does weird stuff with dates which cause issues with BigInt. Adding bool manually. 
For dates people will have to do casting in SQL

2025-01-02 18:08 UTC, archiewood commented on .changeset/soft-carrots-stare.md
> +'@evidence-dev/javascript': patch
updated to source-javascript

2025-01-09 21:53 UTC, ItsMeBrianD requested changes

2025-01-09 21:53 UTC, ItsMeBrianD commented on package.json
> +		"@evidence-dev/javascript": "link:packages/datasources/javascript",
```suggestion
		"@evidence-dev/source-javascript": "link:packages/datasources/javascript",
```

Then this should be good to go

2025-01-13 15:47 UTC, ItsMeBrianD approved these changes

2025-01-13 15:47 UTC, merged