Add a11y to QueryViewer, DownloadData, BreadCrumbs, ECharts, DataTable Components
evidence-dev/evidence pull request #514
Opened 2022-12-13 03:41 UTC by yukseltron

### Description
Part of #489 

Most of these changes involved replacing `spans` with `button` tags and then styling them to match as they were before.

### DownloadData
Turned into a button for a11y.
Made `downloadData` function a prop w/ default.
Hover effect for DownloadData now through CSS in the parent component.
Updated ECharts and DataTable to both use DownloadData, both should still download the appropriate files for the user.

Before (ECharts):

https://user-images.githubusercontent.com/14843458/207218051-c8f5def8-5b56-44fd-a167-e1cb6bbc8f24.mov

After (ECharts):

https://user-images.githubusercontent.com/14843458/207218250-41123c2e-6bbf-42d7-8788-9ec207235f69.mov

Before (DataTable):

https://user-images.githubusercontent.com/14843458/207218701-9dc4aa0c-457f-4cff-b783-793ea3556103.mov

After (DataTable):

https://user-images.githubusercontent.com/14843458/207218923-e24559bb-2124-49c9-beb1-6e1b63f40ab2.mov

### BreadCrumbs
Updated 'Show/Hide Query' to be a11y and is now a button.

Before:

https://user-images.githubusercontent.com/14843458/207219412-733200af-fbc8-47ac-aef1-134a5fa09981.mov

After:

https://user-images.githubusercontent.com/14843458/207219521-726590e6-687d-4656-a92e-e2c42d5aad7a.mov

### QueryViewer
Updated to be a11y and is also now using buttons.

Before:

https://user-images.githubusercontent.com/14843458/207220000-ab9c934b-02e1-4163-b0bd-6ae0870b59a6.mov

After:

https://user-images.githubusercontent.com/14843458/207220121-8b0faec4-ebfb-403f-9242-fcd3fcac0e0c.mov

2022-12-13 12:35 UTC, archiewood commented
I notice in the downloadData video, the styling of the numbers showing the rows seems to have changed in the Before vs After

2022-12-13 13:56 UTC, afzalsayed96 commented
@yukseltron In the interest of semantic correctness, shouldn't `type="button"` also be added to all the `button`s

2022-12-13 14:34 UTC, yukseltron commented
@archiewood restored the styling for pagination.

@afzalsayed96 Yes! Added type='button' to the components.

2022-12-13 15:55 UTC, archiewood requested changes
Looks good overall.

Think the DowloadData is a sensible refactor

A few styling comments for you to look at

2022-12-13 19:46 UTC, yukseltron commented on sites/example-project/src/components/ui/DownloadData.svelte
> -        margin-top: 3px;
Added some margin to the top `10px`.
<img width="299" alt="Screen Shot 2022-12-13 at 2 45 29 PM" src="https://user-images.githubusercontent.com/14843458/207429672-33b0ebf2-3efc-4736-b880-400a2dd15109.png">

2022-12-13 19:47 UTC, yukseltron commented on sites/example-project/src/components/ui/BreadCrumbs.svelte
> +                <button type="button" class="dev-controls hide" on:click={toggleQueries}>Hide Queries</button>
Hide Queries color fixed.


https://user-images.githubusercontent.com/14843458/207429876-37e37771-4847-4ee5-93f9-08d7a361b220.mov

2022-12-13 21:59 UTC, archiewood approved these changes

2022-12-14 14:57 UTC, merged

2022-12-14 15:08 UTC, mcrascal commented
Epic, thank you @yukseltron.