Add Prettier & eslint for code style and pattern enforcement
evidence-dev/evidence pull request #713
Opened 2023-03-24 16:05 UTC by ItsMeBrianD

### Description

This adds prettier and eslint with the default svelte configuration to the project.
A workflow is included that verifies that linting passes to ensure that `main` does not get poorly formatted code.

This should have no impact on downstream projects, and the functionality of the project should remain untouched.

### Checklist
- [ ] ~For UI or styling changes, I have added a screenshot or gif showing before & after~
- [ ] ~I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)~

2023-03-24 16:08 UTC, ItsMeBrianD commented
This is configured correctly; but there are some 400 linting errors to fix. Once most of the currently open PRs are merged; I will merge main into this branch, and then run the formatting and fix the errors to prevent as many merge conflicts as are avoidable.

2023-03-24 17:12 UTC, ud3sh approved these changes

2023-04-12 13:17 UTC, Winterhart requested changes
I strongly suggest to start over from another branch as I can't go over the 400 files to make sure the git items are gone (e.g. `<< HEAD`)

2023-04-12 13:17 UTC, Winterhart commented on packages/preprocess/README.md
> +<<<<<<< HEAD
here too ✂️

2023-04-12 19:52 UTC, Winterhart approved these changes

2023-04-12 21:06 UTC, ud3sh commented
@ItsMeBrianD LGM overall.  If I can mention some pet peeves (other than preferring spaces for tabs of course) `printWidth` seems a bit low at 100 (I tend to have my editors full screen).  But overall, this exact value this is far less important than getting it merged IMO.

2023-04-12 21:42 UTC, mcrascal commented
LGTM -- only build would be adding the tailwind plugin for class sorting.

2023-04-12 21:42 UTC, mcrascal approved these changes

2023-04-13 06:21 UTC, ItsMeBrianD commented
Merging this as is for now; I agree regarding `printWidth`; tailwind class sorting I do think merits a bit of discussion; depends on how we want to style that.

2023-04-13 06:21 UTC, merged