Dropdown menu UI fixes
evidence-dev/evidence pull request #749
Opened 2023-04-10 23:33 UTC by archiewood

### Description
- Click anywhere except on the menu to close
- Expand header bar to 100% on narrow viewports

### Checklist
- [x] For UI or styling changes, I have added a screenshot or gif showing before & after
- [x] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

### Gif
![CleanShot 2023-04-10 at 19 25 38](https://user-images.githubusercontent.com/58074498/231018740-c4e37ee5-56a5-4b19-93aa-5a82230bfb53.gif)

2023-04-10 23:35 UTC, archiewood commented
Todo:
- [ ] Make all drowdown menu items same height (currently `<a>` and `<button>` elements are slightly different heights )

2023-04-10 23:50 UTC, archiewood commented
The click outside to dismiss solution feels a bit gnarly. Would take advice on this if there are other thoughts!

2023-04-11 14:06 UTC, ItsMeBrianD commented
Regarding click outside, here's a library action: https://www.svelteui.org/composables/use- -click-outside, and here's one that I've worked on previously https://github.com/SprocketBot/sprocket/blob/staging/clients/web/src/lib/utils/actions/clickOutsideAction.ts

2023-04-11 15:58 UTC, mcrascal commented
To do: 

- [ ] Look at constraining to article width (e.g. the kebab should be vertically aligned with the right margin of the article, and potentially constraining breadcrumbs alongside it.

2023-04-12 19:19 UTC, archiewood commented
I have a version of the header which constrains the menu and breadcrumbs to article width.

### Before
![CleanShot 2023-04-12 at 14 57 45](https://user-images.githubusercontent.com/58074498/231558181-23c14ec2-a244-43c7-9e34-63afe9394dba.gif)

### After
![CleanShot 2023-04-12 at 14 54 25](https://user-images.githubusercontent.com/58074498/231558112-c237a3db-3614-486c-b3a9-24d3b6d856af.gif)


I'm not totally convinced this is better. Some examples:
## Notion
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/58074498/231559013-f55bb4f0-e1d7-4bf6-bf4a-35309fe53058.png">

## Streamlit
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/58074498/231560705-73a0b24b-0d8f-473f-be42-1fbb78f6e7ac.png">

I think the problem here we're trying to solve is making the menu more obvious. Open to suggestions, but some ideas:
- Make the icon bigger
- Make the icon darker grey
- Change the icon for something more visually eye-catching
- Move some menu items out of the menu
    - Perhaps show/ hide queries as separate icon
    - A generic share icon, that currently only has one option, Export PDF.

2023-04-12 19:34 UTC, ItsMeBrianD commented
@archiewood this may be a helpful tailwind utility for maintaining this behavior:
https://tailwindcss.com/docs/container

2023-04-12 20:00 UTC, mcrascal commented
I'm persuaded for full width. 

Is the preview deploy current? Click outside not working for me in safari.

2023-04-12 20:38 UTC, archiewood commented
ah yeah, me neither. shoulda tested cross browser.

Feels like @ItsMeBrianD's clickoutside action it probably a more robust way to go

2023-04-13 20:04 UTC, ItsMeBrianD requested changes
Looks great, just need to extract clickOutside to it's own file and this should be good to go

2023-04-13 20:04 UTC, ItsMeBrianD commented on sites/example-project/src/components/ui/PageMenu.svelte
>  </script>
This should get moved to it's own file; it's something that we are probably going to want to use in other places.

2023-04-13 23:41 UTC, merged