Add instructions for adapting UI components
evidence-dev/evidence pull request #800
Opened 2023-04-23 19:04 UTC by antaresjhw

### Description

### Checklist

- [ ] For UI or styling changes, I have added a screenshot or gif showing before & after
- [ ] I have added a [changeset](https://github.com/evidence-dev/evidence/blob/main/CONTRIBUTING.md#adding-a-changeset)

(I don't believe these checklist items apply since I am updating documentation only - I'll be happy to adapt if needed).

2023-04-23 19:39 UTC, archiewood requested changes
This is epic, and a really helpful example.

Enough people want to change the project title that I suggest we explicitly call it out in the example, so if people are searching the docs for it, they find it.

We'll probably get to adding this feature pretty soon, so at that point this may be redundant. Until then it's really useful.

A couple of minor wording edits, and I'll merge this!

2023-04-23 19:39 UTC, archiewood commented on sites/docs/docs/components/custom-components.md
> +Adapting any existing components to your needs is straightforward as well. You can achieve this by duplicating an existing component into your `/components` directory, modifying that new component fi
~~Adapting any existing components to your needs is straightforward as well. You can achieve this by duplicating an existing component into your `/components` directory, modifying that new component file, and importing the new component as needed in your project.~~
Modify an existing component by copying the component's source code into the `/components` directory, modifying it, and importing the new component as needed in your project.

2023-04-23 19:39 UTC, archiewood commented on sites/docs/docs/components/custom-components.md
> +## Modifying an existing component
```
## Modifying an existing component: Changing the project name
```

2023-04-23 19:39 UTC, archiewood commented on sites/docs/docs/components/custom-components.md
> +```html title="MySidebar.svelte"
you can use ```svelte as a codefence name and github will highlight it correctly

2023-04-23 19:39 UTC, archiewood commented on sites/docs/docs/components/custom-components.md
> +```javascript title="+layout.svelte"
` ```svelte`

2023-04-23 19:39 UTC, archiewood commented on sites/docs/docs/components/custom-components.md
> +As noted in the comments on one of the snippets above, `$lib` refers to the `component/` directory in the root of our project. Since we didn't change the export name of our component, we only need to
typo:
...refers to the `/components` ...

2023-04-23 19:48 UTC, antaresjhw commented
The requested changes all look great and have been resolved.

2023-04-23 20:07 UTC, ItsMeBrianD approved these changes
Looks awesome!

2023-04-23 20:16 UTC, archiewood commented
@antaresjhw sweet - if it's not totally clear - you'll actually have to commit the changes  - (clicking "resove conversation" on github doesn't actually do anything)

2023-04-23 20:27 UTC, antaresjhw commented
OK, I guess I'm an idiot (or more kindly a GitHub noob). I can't figure out how to actually commit the resolved changes, haha... I'm just using the GitHub web UI. Do I need to do this from my fork? My limited Googling hasn't been much help here, I am afraid.

2023-04-23 21:59 UTC, antaresjhw commented
Thanks for the patience - I think I figured it out and was able to get the suggestions in place. I haven't done any cross-fork PR's, so it was a little bit more "manual" than I guess I was expecting.

2023-04-24 00:00 UTC, archiewood requested changes
Updates look perfect.

Final thing: There seems to be a dead link in here to `components/pages`. This is causing the docs build to fail. Did you perhaps mean `core-concepts/pages`?

2023-04-24 00:54 UTC, antaresjhw commented
Good catch. I made the update, but the build is still failing. It seems like it might be unrelated bo a broken link this time from looking at the details, but I am not completely sure.

2023-04-24 01:04 UTC, archiewood commented
That's actually not the docs - those are some other tests on the software itself. They should definitely pass - I just need to kick them off myself (we ensure a maintainer starts these, as a malicious PR could potentially leak credentials etc).

It's annoying that vercel logs this as a failure, rather than eg "waiting for maintainer to approve" - a bit misleading!

2023-04-24 01:15 UTC, archiewood approved these changes

2023-04-24 01:15 UTC, merged